// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seo.proto

package proto.seo;

public final class SeoProto {
  private SeoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PageSeoDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:seo.PageSeoData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; title = 1;</code>
     */
    int getTitleCount();
    /**
     * <code>map&lt;string, string&gt; title = 1;</code>
     */
    boolean containsTitle(
        java.lang.String key);
    /**
     * Use {@link #getTitleMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getTitle();
    /**
     * <code>map&lt;string, string&gt; title = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getTitleMap();
    /**
     * <code>map&lt;string, string&gt; title = 1;</code>
     */

    java.lang.String getTitleOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; title = 1;</code>
     */

    java.lang.String getTitleOrThrow(
        java.lang.String key);

    /**
     * <code>map&lt;string, string&gt; description = 2;</code>
     */
    int getDescriptionCount();
    /**
     * <code>map&lt;string, string&gt; description = 2;</code>
     */
    boolean containsDescription(
        java.lang.String key);
    /**
     * Use {@link #getDescriptionMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getDescription();
    /**
     * <code>map&lt;string, string&gt; description = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getDescriptionMap();
    /**
     * <code>map&lt;string, string&gt; description = 2;</code>
     */

    java.lang.String getDescriptionOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; description = 2;</code>
     */

    java.lang.String getDescriptionOrThrow(
        java.lang.String key);

    /**
     * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
     */
    java.util.List<proto.seo.SeoProto.PageSeoData.PageSeoTag> 
        getTagsList();
    /**
     * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
     */
    proto.seo.SeoProto.PageSeoData.PageSeoTag getTags(int index);
    /**
     * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
     */
    int getTagsCount();
    /**
     * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
     */
    java.util.List<? extends proto.seo.SeoProto.PageSeoData.PageSeoTagOrBuilder> 
        getTagsOrBuilderList();
    /**
     * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
     */
    proto.seo.SeoProto.PageSeoData.PageSeoTagOrBuilder getTagsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code seo.PageSeoData}
   */
  public  static final class PageSeoData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:seo.PageSeoData)
      PageSeoDataOrBuilder {
    // Use PageSeoData.newBuilder() to construct.
    private PageSeoData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PageSeoData() {
      tags_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PageSeoData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                title_ = com.google.protobuf.MapField.newMapField(
                    TitleDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              title__ = input.readMessage(
                  TitleDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              title_.getMutableMap().put(
                  title__.getKey(), title__.getValue());
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                description_ = com.google.protobuf.MapField.newMapField(
                    DescriptionDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              description__ = input.readMessage(
                  DescriptionDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              description_.getMutableMap().put(
                  description__.getKey(), description__.getValue());
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                tags_ = new java.util.ArrayList<proto.seo.SeoProto.PageSeoData.PageSeoTag>();
                mutable_bitField0_ |= 0x00000004;
              }
              tags_.add(
                  input.readMessage(proto.seo.SeoProto.PageSeoData.PageSeoTag.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          tags_ = java.util.Collections.unmodifiableList(tags_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.seo.SeoProto.internal_static_seo_PageSeoData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetTitle();
        case 2:
          return internalGetDescription();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.seo.SeoProto.internal_static_seo_PageSeoData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.seo.SeoProto.PageSeoData.class, proto.seo.SeoProto.PageSeoData.Builder.class);
    }

    public interface PageSeoTagOrBuilder extends
        // @@protoc_insertion_point(interface_extends:seo.PageSeoData.PageSeoTag)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string tag = 1;</code>
       */
      java.lang.String getTag();
      /**
       * <code>optional string tag = 1;</code>
       */
      com.google.protobuf.ByteString
          getTagBytes();

      /**
       * <code>map&lt;string, string&gt; value = 2;</code>
       */
      int getValueCount();
      /**
       * <code>map&lt;string, string&gt; value = 2;</code>
       */
      boolean containsValue(
          java.lang.String key);
      /**
       * Use {@link #getValueMap()} instead.
       */
      @java.lang.Deprecated
      java.util.Map<java.lang.String, java.lang.String>
      getValue();
      /**
       * <code>map&lt;string, string&gt; value = 2;</code>
       */
      java.util.Map<java.lang.String, java.lang.String>
      getValueMap();
      /**
       * <code>map&lt;string, string&gt; value = 2;</code>
       */

      java.lang.String getValueOrDefault(
          java.lang.String key,
          java.lang.String defaultValue);
      /**
       * <code>map&lt;string, string&gt; value = 2;</code>
       */

      java.lang.String getValueOrThrow(
          java.lang.String key);
    }
    /**
     * Protobuf type {@code seo.PageSeoData.PageSeoTag}
     */
    public  static final class PageSeoTag extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:seo.PageSeoData.PageSeoTag)
        PageSeoTagOrBuilder {
      // Use PageSeoTag.newBuilder() to construct.
      private PageSeoTag(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PageSeoTag() {
        tag_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private PageSeoTag(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                tag_ = s;
                break;
              }
              case 18: {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  value_ = com.google.protobuf.MapField.newMapField(
                      ValueDefaultEntryHolder.defaultEntry);
                  mutable_bitField0_ |= 0x00000002;
                }
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                value__ = input.readMessage(
                    ValueDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                value_.getMutableMap().put(
                    value__.getKey(), value__.getValue());
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.seo.SeoProto.internal_static_seo_PageSeoData_PageSeoTag_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetValue();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.seo.SeoProto.internal_static_seo_PageSeoData_PageSeoTag_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.seo.SeoProto.PageSeoData.PageSeoTag.class, proto.seo.SeoProto.PageSeoData.PageSeoTag.Builder.class);
      }

      private int bitField0_;
      public static final int TAG_FIELD_NUMBER = 1;
      private volatile java.lang.Object tag_;
      /**
       * <code>optional string tag = 1;</code>
       */
      public java.lang.String getTag() {
        java.lang.Object ref = tag_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tag_ = s;
          return s;
        }
      }
      /**
       * <code>optional string tag = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTagBytes() {
        java.lang.Object ref = tag_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private static final class ValueDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<
            java.lang.String, java.lang.String> defaultEntry =
                com.google.protobuf.MapEntry
                .<java.lang.String, java.lang.String>newDefaultInstance(
                    proto.seo.SeoProto.internal_static_seo_PageSeoData_PageSeoTag_ValueEntry_descriptor, 
                    com.google.protobuf.WireFormat.FieldType.STRING,
                    "",
                    com.google.protobuf.WireFormat.FieldType.STRING,
                    "");
      }
      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> value_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetValue() {
        if (value_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ValueDefaultEntryHolder.defaultEntry);
        }
        return value_;
      }

      public int getValueCount() {
        return internalGetValue().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; value = 2;</code>
       */

      public boolean containsValue(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetValue().getMap().containsKey(key);
      }
      /**
       * Use {@link #getValueMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getValue() {
        return getValueMap();
      }
      /**
       * <code>map&lt;string, string&gt; value = 2;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getValueMap() {
        return internalGetValue().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; value = 2;</code>
       */

      public java.lang.String getValueOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetValue().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; value = 2;</code>
       */

      public java.lang.String getValueOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetValue().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getTagBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tag_);
        }
        com.google.protobuf.GeneratedMessageV3
          .serializeStringMapTo(
            output,
            internalGetValue(),
            ValueDefaultEntryHolder.defaultEntry,
            2);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getTagBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tag_);
        }
        for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
             : internalGetValue().getMap().entrySet()) {
          com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
          value__ = ValueDefaultEntryHolder.defaultEntry.newBuilderForType()
              .setKey(entry.getKey())
              .setValue(entry.getValue())
              .build();
          size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(2, value__);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof proto.seo.SeoProto.PageSeoData.PageSeoTag)) {
          return super.equals(obj);
        }
        proto.seo.SeoProto.PageSeoData.PageSeoTag other = (proto.seo.SeoProto.PageSeoData.PageSeoTag) obj;

        boolean result = true;
        result = result && getTag()
            .equals(other.getTag());
        result = result && internalGetValue().equals(
            other.internalGetValue());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + TAG_FIELD_NUMBER;
        hash = (53 * hash) + getTag().hashCode();
        if (!internalGetValue().getMap().isEmpty()) {
          hash = (37 * hash) + VALUE_FIELD_NUMBER;
          hash = (53 * hash) + internalGetValue().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static proto.seo.SeoProto.PageSeoData.PageSeoTag parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static proto.seo.SeoProto.PageSeoData.PageSeoTag parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static proto.seo.SeoProto.PageSeoData.PageSeoTag parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static proto.seo.SeoProto.PageSeoData.PageSeoTag parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static proto.seo.SeoProto.PageSeoData.PageSeoTag parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static proto.seo.SeoProto.PageSeoData.PageSeoTag parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static proto.seo.SeoProto.PageSeoData.PageSeoTag parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static proto.seo.SeoProto.PageSeoData.PageSeoTag parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static proto.seo.SeoProto.PageSeoData.PageSeoTag parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static proto.seo.SeoProto.PageSeoData.PageSeoTag parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(proto.seo.SeoProto.PageSeoData.PageSeoTag prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code seo.PageSeoData.PageSeoTag}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:seo.PageSeoData.PageSeoTag)
          proto.seo.SeoProto.PageSeoData.PageSeoTagOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return proto.seo.SeoProto.internal_static_seo_PageSeoData_PageSeoTag_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
            int number) {
          switch (number) {
            case 2:
              return internalGetValue();
            default:
              throw new RuntimeException(
                  "Invalid map field number: " + number);
          }
        }
        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMutableMapField(
            int number) {
          switch (number) {
            case 2:
              return internalGetMutableValue();
            default:
              throw new RuntimeException(
                  "Invalid map field number: " + number);
          }
        }
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return proto.seo.SeoProto.internal_static_seo_PageSeoData_PageSeoTag_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  proto.seo.SeoProto.PageSeoData.PageSeoTag.class, proto.seo.SeoProto.PageSeoData.PageSeoTag.Builder.class);
        }

        // Construct using proto.seo.SeoProto.PageSeoData.PageSeoTag.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          tag_ = "";

          internalGetMutableValue().clear();
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return proto.seo.SeoProto.internal_static_seo_PageSeoData_PageSeoTag_descriptor;
        }

        public proto.seo.SeoProto.PageSeoData.PageSeoTag getDefaultInstanceForType() {
          return proto.seo.SeoProto.PageSeoData.PageSeoTag.getDefaultInstance();
        }

        public proto.seo.SeoProto.PageSeoData.PageSeoTag build() {
          proto.seo.SeoProto.PageSeoData.PageSeoTag result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public proto.seo.SeoProto.PageSeoData.PageSeoTag buildPartial() {
          proto.seo.SeoProto.PageSeoData.PageSeoTag result = new proto.seo.SeoProto.PageSeoData.PageSeoTag(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          result.tag_ = tag_;
          result.value_ = internalGetValue();
          result.value_.makeImmutable();
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof proto.seo.SeoProto.PageSeoData.PageSeoTag) {
            return mergeFrom((proto.seo.SeoProto.PageSeoData.PageSeoTag)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(proto.seo.SeoProto.PageSeoData.PageSeoTag other) {
          if (other == proto.seo.SeoProto.PageSeoData.PageSeoTag.getDefaultInstance()) return this;
          if (!other.getTag().isEmpty()) {
            tag_ = other.tag_;
            onChanged();
          }
          internalGetMutableValue().mergeFrom(
              other.internalGetValue());
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          proto.seo.SeoProto.PageSeoData.PageSeoTag parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (proto.seo.SeoProto.PageSeoData.PageSeoTag) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object tag_ = "";
        /**
         * <code>optional string tag = 1;</code>
         */
        public java.lang.String getTag() {
          java.lang.Object ref = tag_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            tag_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string tag = 1;</code>
         */
        public com.google.protobuf.ByteString
            getTagBytes() {
          java.lang.Object ref = tag_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            tag_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string tag = 1;</code>
         */
        public Builder setTag(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          tag_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string tag = 1;</code>
         */
        public Builder clearTag() {
          
          tag_ = getDefaultInstance().getTag();
          onChanged();
          return this;
        }
        /**
         * <code>optional string tag = 1;</code>
         */
        public Builder setTagBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          tag_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.MapField<
            java.lang.String, java.lang.String> value_;
        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetValue() {
          if (value_ == null) {
            return com.google.protobuf.MapField.emptyMapField(
                ValueDefaultEntryHolder.defaultEntry);
          }
          return value_;
        }
        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableValue() {
          onChanged();;
          if (value_ == null) {
            value_ = com.google.protobuf.MapField.newMapField(
                ValueDefaultEntryHolder.defaultEntry);
          }
          if (!value_.isMutable()) {
            value_ = value_.copy();
          }
          return value_;
        }

        public int getValueCount() {
          return internalGetValue().getMap().size();
        }
        /**
         * <code>map&lt;string, string&gt; value = 2;</code>
         */

        public boolean containsValue(
            java.lang.String key) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          return internalGetValue().getMap().containsKey(key);
        }
        /**
         * Use {@link #getValueMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getValue() {
          return getValueMap();
        }
        /**
         * <code>map&lt;string, string&gt; value = 2;</code>
         */

        public java.util.Map<java.lang.String, java.lang.String> getValueMap() {
          return internalGetValue().getMap();
        }
        /**
         * <code>map&lt;string, string&gt; value = 2;</code>
         */

        public java.lang.String getValueOrDefault(
            java.lang.String key,
            java.lang.String defaultValue) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          java.util.Map<java.lang.String, java.lang.String> map =
              internalGetValue().getMap();
          return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;string, string&gt; value = 2;</code>
         */

        public java.lang.String getValueOrThrow(
            java.lang.String key) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          java.util.Map<java.lang.String, java.lang.String> map =
              internalGetValue().getMap();
          if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
          }
          return map.get(key);
        }

        public Builder clearValue() {
          getMutableValue().clear();
          return this;
        }
        /**
         * <code>map&lt;string, string&gt; value = 2;</code>
         */

        public Builder removeValue(
            java.lang.String key) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          getMutableValue().remove(key);
          return this;
        }
        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String>
        getMutableValue() {
          return internalGetMutableValue().getMutableMap();
        }
        /**
         * <code>map&lt;string, string&gt; value = 2;</code>
         */
        public Builder putValue(
            java.lang.String key,
            java.lang.String value) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          if (value == null) { throw new java.lang.NullPointerException(); }
          getMutableValue().put(key, value);
          return this;
        }
        /**
         * <code>map&lt;string, string&gt; value = 2;</code>
         */

        public Builder putAllValue(
            java.util.Map<java.lang.String, java.lang.String> values) {
          getMutableValue().putAll(values);
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:seo.PageSeoData.PageSeoTag)
      }

      // @@protoc_insertion_point(class_scope:seo.PageSeoData.PageSeoTag)
      private static final proto.seo.SeoProto.PageSeoData.PageSeoTag DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new proto.seo.SeoProto.PageSeoData.PageSeoTag();
      }

      public static proto.seo.SeoProto.PageSeoData.PageSeoTag getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PageSeoTag>
          PARSER = new com.google.protobuf.AbstractParser<PageSeoTag>() {
        public PageSeoTag parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new PageSeoTag(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<PageSeoTag> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PageSeoTag> getParserForType() {
        return PARSER;
      }

      public proto.seo.SeoProto.PageSeoData.PageSeoTag getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int TITLE_FIELD_NUMBER = 1;
    private static final class TitleDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  proto.seo.SeoProto.internal_static_seo_PageSeoData_TitleEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> title_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetTitle() {
      if (title_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TitleDefaultEntryHolder.defaultEntry);
      }
      return title_;
    }

    public int getTitleCount() {
      return internalGetTitle().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; title = 1;</code>
     */

    public boolean containsTitle(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTitle().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTitleMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTitle() {
      return getTitleMap();
    }
    /**
     * <code>map&lt;string, string&gt; title = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getTitleMap() {
      return internalGetTitle().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; title = 1;</code>
     */

    public java.lang.String getTitleOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTitle().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; title = 1;</code>
     */

    public java.lang.String getTitleOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTitle().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private static final class DescriptionDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  proto.seo.SeoProto.internal_static_seo_PageSeoData_DescriptionEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> description_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetDescription() {
      if (description_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DescriptionDefaultEntryHolder.defaultEntry);
      }
      return description_;
    }

    public int getDescriptionCount() {
      return internalGetDescription().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; description = 2;</code>
     */

    public boolean containsDescription(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetDescription().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDescriptionMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getDescription() {
      return getDescriptionMap();
    }
    /**
     * <code>map&lt;string, string&gt; description = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getDescriptionMap() {
      return internalGetDescription().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; description = 2;</code>
     */

    public java.lang.String getDescriptionOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetDescription().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; description = 2;</code>
     */

    public java.lang.String getDescriptionOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetDescription().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int TAGS_FIELD_NUMBER = 3;
    private java.util.List<proto.seo.SeoProto.PageSeoData.PageSeoTag> tags_;
    /**
     * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
     */
    public java.util.List<proto.seo.SeoProto.PageSeoData.PageSeoTag> getTagsList() {
      return tags_;
    }
    /**
     * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
     */
    public java.util.List<? extends proto.seo.SeoProto.PageSeoData.PageSeoTagOrBuilder> 
        getTagsOrBuilderList() {
      return tags_;
    }
    /**
     * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
     */
    public proto.seo.SeoProto.PageSeoData.PageSeoTag getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
     */
    public proto.seo.SeoProto.PageSeoData.PageSeoTagOrBuilder getTagsOrBuilder(
        int index) {
      return tags_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTitle(),
          TitleDefaultEntryHolder.defaultEntry,
          1);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetDescription(),
          DescriptionDefaultEntryHolder.defaultEntry,
          2);
      for (int i = 0; i < tags_.size(); i++) {
        output.writeMessage(3, tags_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetTitle().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        title__ = TitleDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, title__);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetDescription().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        description__ = DescriptionDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, description__);
      }
      for (int i = 0; i < tags_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, tags_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.seo.SeoProto.PageSeoData)) {
        return super.equals(obj);
      }
      proto.seo.SeoProto.PageSeoData other = (proto.seo.SeoProto.PageSeoData) obj;

      boolean result = true;
      result = result && internalGetTitle().equals(
          other.internalGetTitle());
      result = result && internalGetDescription().equals(
          other.internalGetDescription());
      result = result && getTagsList()
          .equals(other.getTagsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (!internalGetTitle().getMap().isEmpty()) {
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTitle().hashCode();
      }
      if (!internalGetDescription().getMap().isEmpty()) {
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + internalGetDescription().hashCode();
      }
      if (getTagsCount() > 0) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getTagsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.seo.SeoProto.PageSeoData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.seo.SeoProto.PageSeoData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.seo.SeoProto.PageSeoData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.seo.SeoProto.PageSeoData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.seo.SeoProto.PageSeoData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.seo.SeoProto.PageSeoData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.seo.SeoProto.PageSeoData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.seo.SeoProto.PageSeoData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.seo.SeoProto.PageSeoData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.seo.SeoProto.PageSeoData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.seo.SeoProto.PageSeoData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code seo.PageSeoData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:seo.PageSeoData)
        proto.seo.SeoProto.PageSeoDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.seo.SeoProto.internal_static_seo_PageSeoData_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetTitle();
          case 2:
            return internalGetDescription();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableTitle();
          case 2:
            return internalGetMutableDescription();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.seo.SeoProto.internal_static_seo_PageSeoData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.seo.SeoProto.PageSeoData.class, proto.seo.SeoProto.PageSeoData.Builder.class);
      }

      // Construct using proto.seo.SeoProto.PageSeoData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTagsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableTitle().clear();
        internalGetMutableDescription().clear();
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          tagsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.seo.SeoProto.internal_static_seo_PageSeoData_descriptor;
      }

      public proto.seo.SeoProto.PageSeoData getDefaultInstanceForType() {
        return proto.seo.SeoProto.PageSeoData.getDefaultInstance();
      }

      public proto.seo.SeoProto.PageSeoData build() {
        proto.seo.SeoProto.PageSeoData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.seo.SeoProto.PageSeoData buildPartial() {
        proto.seo.SeoProto.PageSeoData result = new proto.seo.SeoProto.PageSeoData(this);
        int from_bitField0_ = bitField0_;
        result.title_ = internalGetTitle();
        result.title_.makeImmutable();
        result.description_ = internalGetDescription();
        result.description_.makeImmutable();
        if (tagsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            tags_ = java.util.Collections.unmodifiableList(tags_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.tags_ = tags_;
        } else {
          result.tags_ = tagsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.seo.SeoProto.PageSeoData) {
          return mergeFrom((proto.seo.SeoProto.PageSeoData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.seo.SeoProto.PageSeoData other) {
        if (other == proto.seo.SeoProto.PageSeoData.getDefaultInstance()) return this;
        internalGetMutableTitle().mergeFrom(
            other.internalGetTitle());
        internalGetMutableDescription().mergeFrom(
            other.internalGetDescription());
        if (tagsBuilder_ == null) {
          if (!other.tags_.isEmpty()) {
            if (tags_.isEmpty()) {
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureTagsIsMutable();
              tags_.addAll(other.tags_);
            }
            onChanged();
          }
        } else {
          if (!other.tags_.isEmpty()) {
            if (tagsBuilder_.isEmpty()) {
              tagsBuilder_.dispose();
              tagsBuilder_ = null;
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000004);
              tagsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTagsFieldBuilder() : null;
            } else {
              tagsBuilder_.addAllMessages(other.tags_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.seo.SeoProto.PageSeoData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.seo.SeoProto.PageSeoData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> title_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetTitle() {
        if (title_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TitleDefaultEntryHolder.defaultEntry);
        }
        return title_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableTitle() {
        onChanged();;
        if (title_ == null) {
          title_ = com.google.protobuf.MapField.newMapField(
              TitleDefaultEntryHolder.defaultEntry);
        }
        if (!title_.isMutable()) {
          title_ = title_.copy();
        }
        return title_;
      }

      public int getTitleCount() {
        return internalGetTitle().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; title = 1;</code>
       */

      public boolean containsTitle(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTitle().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTitleMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getTitle() {
        return getTitleMap();
      }
      /**
       * <code>map&lt;string, string&gt; title = 1;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getTitleMap() {
        return internalGetTitle().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; title = 1;</code>
       */

      public java.lang.String getTitleOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTitle().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; title = 1;</code>
       */

      public java.lang.String getTitleOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTitle().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTitle() {
        getMutableTitle().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; title = 1;</code>
       */

      public Builder removeTitle(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableTitle().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableTitle() {
        return internalGetMutableTitle().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; title = 1;</code>
       */
      public Builder putTitle(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableTitle().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; title = 1;</code>
       */

      public Builder putAllTitle(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableTitle().putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> description_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetDescription() {
        if (description_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              DescriptionDefaultEntryHolder.defaultEntry);
        }
        return description_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableDescription() {
        onChanged();;
        if (description_ == null) {
          description_ = com.google.protobuf.MapField.newMapField(
              DescriptionDefaultEntryHolder.defaultEntry);
        }
        if (!description_.isMutable()) {
          description_ = description_.copy();
        }
        return description_;
      }

      public int getDescriptionCount() {
        return internalGetDescription().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; description = 2;</code>
       */

      public boolean containsDescription(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetDescription().getMap().containsKey(key);
      }
      /**
       * Use {@link #getDescriptionMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getDescription() {
        return getDescriptionMap();
      }
      /**
       * <code>map&lt;string, string&gt; description = 2;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getDescriptionMap() {
        return internalGetDescription().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; description = 2;</code>
       */

      public java.lang.String getDescriptionOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetDescription().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; description = 2;</code>
       */

      public java.lang.String getDescriptionOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetDescription().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearDescription() {
        getMutableDescription().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; description = 2;</code>
       */

      public Builder removeDescription(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableDescription().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableDescription() {
        return internalGetMutableDescription().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; description = 2;</code>
       */
      public Builder putDescription(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableDescription().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; description = 2;</code>
       */

      public Builder putAllDescription(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableDescription().putAll(values);
        return this;
      }

      private java.util.List<proto.seo.SeoProto.PageSeoData.PageSeoTag> tags_ =
        java.util.Collections.emptyList();
      private void ensureTagsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          tags_ = new java.util.ArrayList<proto.seo.SeoProto.PageSeoData.PageSeoTag>(tags_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.seo.SeoProto.PageSeoData.PageSeoTag, proto.seo.SeoProto.PageSeoData.PageSeoTag.Builder, proto.seo.SeoProto.PageSeoData.PageSeoTagOrBuilder> tagsBuilder_;

      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public java.util.List<proto.seo.SeoProto.PageSeoData.PageSeoTag> getTagsList() {
        if (tagsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tags_);
        } else {
          return tagsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public int getTagsCount() {
        if (tagsBuilder_ == null) {
          return tags_.size();
        } else {
          return tagsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public proto.seo.SeoProto.PageSeoData.PageSeoTag getTags(int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);
        } else {
          return tagsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public Builder setTags(
          int index, proto.seo.SeoProto.PageSeoData.PageSeoTag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.set(index, value);
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public Builder setTags(
          int index, proto.seo.SeoProto.PageSeoData.PageSeoTag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public Builder addTags(proto.seo.SeoProto.PageSeoData.PageSeoTag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public Builder addTags(
          int index, proto.seo.SeoProto.PageSeoData.PageSeoTag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(index, value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public Builder addTags(
          proto.seo.SeoProto.PageSeoData.PageSeoTag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public Builder addTags(
          int index, proto.seo.SeoProto.PageSeoData.PageSeoTag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public Builder addAllTags(
          java.lang.Iterable<? extends proto.seo.SeoProto.PageSeoData.PageSeoTag> values) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tags_);
          onChanged();
        } else {
          tagsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public Builder clearTags() {
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          tagsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public Builder removeTags(int index) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.remove(index);
          onChanged();
        } else {
          tagsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public proto.seo.SeoProto.PageSeoData.PageSeoTag.Builder getTagsBuilder(
          int index) {
        return getTagsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public proto.seo.SeoProto.PageSeoData.PageSeoTagOrBuilder getTagsOrBuilder(
          int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);  } else {
          return tagsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public java.util.List<? extends proto.seo.SeoProto.PageSeoData.PageSeoTagOrBuilder> 
           getTagsOrBuilderList() {
        if (tagsBuilder_ != null) {
          return tagsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tags_);
        }
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public proto.seo.SeoProto.PageSeoData.PageSeoTag.Builder addTagsBuilder() {
        return getTagsFieldBuilder().addBuilder(
            proto.seo.SeoProto.PageSeoData.PageSeoTag.getDefaultInstance());
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public proto.seo.SeoProto.PageSeoData.PageSeoTag.Builder addTagsBuilder(
          int index) {
        return getTagsFieldBuilder().addBuilder(
            index, proto.seo.SeoProto.PageSeoData.PageSeoTag.getDefaultInstance());
      }
      /**
       * <code>repeated .seo.PageSeoData.PageSeoTag tags = 3;</code>
       */
      public java.util.List<proto.seo.SeoProto.PageSeoData.PageSeoTag.Builder> 
           getTagsBuilderList() {
        return getTagsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.seo.SeoProto.PageSeoData.PageSeoTag, proto.seo.SeoProto.PageSeoData.PageSeoTag.Builder, proto.seo.SeoProto.PageSeoData.PageSeoTagOrBuilder> 
          getTagsFieldBuilder() {
        if (tagsBuilder_ == null) {
          tagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.seo.SeoProto.PageSeoData.PageSeoTag, proto.seo.SeoProto.PageSeoData.PageSeoTag.Builder, proto.seo.SeoProto.PageSeoData.PageSeoTagOrBuilder>(
                  tags_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          tags_ = null;
        }
        return tagsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:seo.PageSeoData)
    }

    // @@protoc_insertion_point(class_scope:seo.PageSeoData)
    private static final proto.seo.SeoProto.PageSeoData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.seo.SeoProto.PageSeoData();
    }

    public static proto.seo.SeoProto.PageSeoData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PageSeoData>
        PARSER = new com.google.protobuf.AbstractParser<PageSeoData>() {
      public PageSeoData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PageSeoData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PageSeoData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PageSeoData> getParserForType() {
      return PARSER;
    }

    public proto.seo.SeoProto.PageSeoData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_seo_PageSeoData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_seo_PageSeoData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_seo_PageSeoData_PageSeoTag_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_seo_PageSeoData_PageSeoTag_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_seo_PageSeoData_PageSeoTag_ValueEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_seo_PageSeoData_PageSeoTag_ValueEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_seo_PageSeoData_TitleEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_seo_PageSeoData_TitleEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_seo_PageSeoData_DescriptionEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_seo_PageSeoData_DescriptionEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tseo.proto\022\003seo\"\376\002\n\013PageSeoData\022*\n\005titl" +
      "e\030\001 \003(\0132\033.seo.PageSeoData.TitleEntry\0226\n\013" +
      "description\030\002 \003(\0132!.seo.PageSeoData.Desc" +
      "riptionEntry\022)\n\004tags\030\003 \003(\0132\033.seo.PageSeo" +
      "Data.PageSeoTag\032~\n\nPageSeoTag\022\013\n\003tag\030\001 \001" +
      "(\t\0225\n\005value\030\002 \003(\0132&.seo.PageSeoData.Page" +
      "SeoTag.ValueEntry\032,\n\nValueEntry\022\013\n\003key\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032,\n\nTitleEntry\022\013\n" +
      "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\0322\n\020Descrip" +
      "tionEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028",
      "\001B\025\n\tproto.seoB\010SeoProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_seo_PageSeoData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_seo_PageSeoData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_seo_PageSeoData_descriptor,
        new java.lang.String[] { "Title", "Description", "Tags", });
    internal_static_seo_PageSeoData_PageSeoTag_descriptor =
      internal_static_seo_PageSeoData_descriptor.getNestedTypes().get(0);
    internal_static_seo_PageSeoData_PageSeoTag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_seo_PageSeoData_PageSeoTag_descriptor,
        new java.lang.String[] { "Tag", "Value", });
    internal_static_seo_PageSeoData_PageSeoTag_ValueEntry_descriptor =
      internal_static_seo_PageSeoData_PageSeoTag_descriptor.getNestedTypes().get(0);
    internal_static_seo_PageSeoData_PageSeoTag_ValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_seo_PageSeoData_PageSeoTag_ValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_seo_PageSeoData_TitleEntry_descriptor =
      internal_static_seo_PageSeoData_descriptor.getNestedTypes().get(1);
    internal_static_seo_PageSeoData_TitleEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_seo_PageSeoData_TitleEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_seo_PageSeoData_DescriptionEntry_descriptor =
      internal_static_seo_PageSeoData_descriptor.getNestedTypes().get(2);
    internal_static_seo_PageSeoData_DescriptionEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_seo_PageSeoData_DescriptionEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
